server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          # routes va dentro de webflux también
          routes:
            # - id: orders-service
            #   uri: lb://orders-service
            #   predicates:
            #     - Path=/api/orders/**
            #   filters:
            #     - StripPrefix=1
